### ISSUE TITLE
reimplemented assorted settings

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#422]
This tracks porting the Settings app features to Nougat, other than the split encryption password feature which has to be dealt with as another project.

- [ ] security vs. performance slider https://github.com/copperhead/bugtracker/issues/410
- [ ] malloc configuration options https://github.com/copperhead/bugtracker/issues/409
- [x] deny usb setting https://github.com/copperhead/bugtracker/issues/407

**Comment by thestinger** [comment]
The other features are going to be revisited and perhaps redesigned.
